### ISSUE TITLE
🇩🇪 Warum ist es auf Englisch?

### ISSUE THREAD

**Issue by szepeviktor** [EngineeringKiosk/GermanTechPodcasts#29]
@andygrunwald What is the point of listing German things in English?

**Comment by woolfg** [comment]
German software is also commented in English and maybe we want to use the code for English podcasts in the future as well?

**Comment by szepeviktor** [comment]
I haven't even noticed there is source code :)

I mean the README!
https://github.com/EngineeringKiosk/GermanTechPodcasts/pull/52/files 👀

**Comment by szepeviktor** [comment]
@woolfg To be honest I'm not here to argue and to send PR-s
but **to inspire**.

**Comment by andygrunwald** [comment]
@szepeviktor, Which is great, and we appreciate your input a lot. Thanks for this.

To be honest: Wolfgang and I also discussed the primary language of this repository. He voted for Englisch, I for German. In the end, we went for English and German. What? Let me explain.

On GitHub, the primary language is English. Mainly because the engineering community primarily communicates in English (yeah, there are also a lot of Chinese repositories). Hence we went for English in the GitHub version.
This leads to a language mix in the README.md, because the titles and descriptions of the podcasts are german. I think this is the tradeoff for our decision here.

On the Engineering Kiosk website (https://engineeringkiosk.dev/deutsche-tech-podcasts/), we have a german version available. 

We hope this shares a bit of our thought process. Let me know what you think.

**Comment by szepeviktor** [comment]
Thank you for revealing this esoteric depth of using languages.

**Comment by woolfg** [comment]
>  To be honest I'm not here to argue and to send PR-s but **to inspire**.

thanks @szepeviktor for the inspiration ;) ... we are still dicussing this issue and try find a good solution for it but I guess we won't find an ideal solution.

**Comment by woolfg** [comment]
>  To be honest I'm not here to argue and to send PR-s but **to inspire**.

thanks @szepeviktor for the inspiration ;) ... we are still dicussing this issue and try find a good solution for it but I guess we won't find an ideal solution.
